### ISSUE TITLE
GPLv3 Palc - allowed?

### ISSUE THREAD

**Issue by TheTechRobo** [TheTechRobo/python-text-calculator#26]
@JasonG-FR : When you submitted your translation corrections (thanks again!), Palc was licensed under the DBAD License. I want to change it to GPL 3.0 to make it actually open source - are you OK with this? 

@lewiswatson55 : When I forked your calculator to make Palc, it had no license. Is it OK for me to put it on GNU GPL 3.0? (Right now it's on the DBAD License, which I'm wondering if it's OK too.) Sorry for not asking you at the start - I didn't know that no license meant you can't necessarily add one.

Thanks in advance! :)

**Comment by lewiswatson55** [comment]
Hey, yeah no problem. Thanks for still crediting even tho you've got basically none of the original code! Love what you're doing with Palc!

**Comment by TheTechRobo** [comment]
@lewiswatson55 Thanks so much! :D

**Comment by JasonG-FR** [comment]
I'm absolutely fine with it :)

**Comment by TheTechRobo** [comment]
Thanks @jasong-fr ! :)

**Comment by TheTechRobo** [comment]
@Shankhalika @harish123456798 @marloncard @alistairdev @AshutoshInfy Sorry for the ping but I realised I should ask if it's ok to you guys too, as contributors to the original repo. Is it ok for me to license Palc under gplv3? thanks.

**Comment by alistairdev** [comment]
@TheTechRobo Yes, I have no objections 😀

**Comment by TheTechRobo** [comment]
Additionally, what do you guys think of switching the license of mathmod **only** (not Palc) to the LGPL?

I'm sorry for bugging you all but I just want to have the best license and I want everyone to agree.
